services:
  - type: web
    name: myfilmpeople-web
    runtime: python
    plan: standard
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 4 --worker-class gthread --timeout 60 --max-requests 1000 --max-requests-jitter 100 --log-level info
    
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "myfilmpeople.onrender.com"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_TIMEOUT
        value: "10"
      - key: REDIS_URL
        fromService:
          type: redis
          name: myfilmpeople-redis
          property: connectionString

  - type: redis
    name: myfilmpeople-redis
    plan: standard
    ipAllowList: []
