# Generated by Django 5.1.6 on 2026-05-31 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('min_count', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-level', '-created_at'],
            },
        ),
    ]
