"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
import dj_database_url

from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (if present)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-*3p%s&!9mpa%%v5=co@@^=iz$0vjsb)(sy2s$w131^%=*f)6dm",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0") == "1"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()]

# Developer convenience: allow LAN/mobile access in DEBUG without constantly
# updating ALLOWED_HOSTS for changing IPs.
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("*")

# Render.com deployment: automatically add render domain
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.humanize',

    'accounts',
    'catalog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.new_arrivals_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Hosted PostgreSQL deployments can be configured through DATABASE_URL.

if os.getenv("DATABASE_URL"):
    # Production / hosted PostgreSQL: use DATABASE_URL.
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development: use MySQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "myfilmpeople"),
            "USER": os.getenv("DB_USER", "root"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
                # Increase session sort buffer to avoid MySQL "Out of sort memory" errors
                # for large ORDER BY operations in local dev. Value is bytes (8MB).
                "init_command": "SET SESSION sort_buffer_size=8388608",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for production static file serving.
# During tests, use non-manifest storage so template rendering does not depend
# on collectstatic having been run.
if any(arg == "test" for arg in sys.argv):
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "home"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Email delivery for signup OTPs.
# Brevo works through Django's standard SMTP backend. In development we fall
# back to console output unless explicit email credentials are configured.
if any(arg == "test" for arg in sys.argv):
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
elif os.getenv("EMAIL_HOST") or os.getenv("BREVO_SMTP_HOST"):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", os.getenv("BREVO_SMTP_HOST", ""))
EMAIL_PORT = int(os.getenv("EMAIL_PORT", os.getenv("BREVO_SMTP_PORT", "587")))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", os.getenv("BREVO_SMTP_USER", ""))
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", os.getenv("BREVO_SMTP_PASSWORD", ""))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", os.getenv("BREVO_SMTP_USE_TLS", "1")) == "1"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", os.getenv("BREVO_SMTP_USE_SSL", "0")) == "1"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
BREVO_API_KEY = os.getenv("BREVO_API_KEY", os.getenv("BREVO_SMTP_API_KEY", ""))
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    os.getenv("BREVO_FROM_EMAIL", "MyFilmPeople <no-reply@myfilmpeople.local>"),
)

# TMDb
TMDB_API_KEY = os.getenv("TMDB_API_KEY", "")
TMDB_API_READ_ACCESS_TOKEN = os.getenv("TMDB_API_READ_ACCESS_TOKEN", "")
TMDB_LANGUAGE = os.getenv("TMDB_LANGUAGE", "en-US")
TMDB_REGION = os.getenv("TMDB_REGION", "")
TMDB_CACHE_TTL_HOURS = int(os.getenv("TMDB_CACHE_TTL_HOURS", "168"))
MOVIE_STALE_DELETE_DAYS = int(os.getenv("MOVIE_STALE_DELETE_DAYS", "5"))
TMDB_PERSON_COMEBACK_GAP_YEARS = int(os.getenv("TMDB_PERSON_COMEBACK_GAP_YEARS", "5"))

# New: separate thresholds
# How long without releases to consider a person "inactive" on UI badges (default 10 years).
TMDB_PERSON_INACTIVE_THRESHOLD_YEARS = int(
    os.getenv("TMDB_PERSON_INACTIVE_THRESHOLD_YEARS", "10")
)
# How large a gap to treat a later credit as a "comeback" (default 5 years).
TMDB_PERSON_COMEBACK_THRESHOLD_YEARS = int(
    os.getenv("TMDB_PERSON_COMEBACK_THRESHOLD_YEARS", "5")
)


# Redis / Django cache
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")
REDIS_KEY_PREFIX = os.getenv("REDIS_KEY_PREFIX", "myfilmpeople")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Fail open if Redis is down (treat as cache-miss).
            "IGNORE_EXCEPTIONS": True,
        },
        "KEY_PREFIX": REDIS_KEY_PREFIX,
    }
}

# Use the database-backed session store with cache acceleration.
# This keeps critical auth flows working even if Redis is slow or temporarily
# unavailable, while still benefiting from the configured cache when it is up.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"


def _split_csv_env(value: str) -> list[str]:
    return [x.strip() for x in (value or "").split(",") if x.strip()]


# Optional: fallback proxies for environments where TMDb is blocked.
# Used server-side (Django -> TMDb), not for browser CORS.
CORS_PROXIES = _split_csv_env(
    os.getenv(
        "CORS_PROXIES",
        "https://api.allorigins.win/raw?url=,https://corsproxy.io/?,https://cors-anywhere.herokuapp.com/,https://api.codetabs.com/v1/proxy?quest=,https://yacdn.org/proxy/",
    )
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Basic logging configuration (console output by default)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '%(levelname)s %(asctime)s %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('LOG_LEVEL', 'INFO'),
    },
}


# Production security defaults and sanity checks
if not DEBUG:
    # Require an explicit, non-default secret key in production
    if not SECRET_KEY or SECRET_KEY in ("change-me",) or SECRET_KEY.startswith("django-insecure-"):
        raise RuntimeError(
            "SECRET_KEY is not set to a secure value. Set the SECRET_KEY environment variable for production."
        )

    # Ensure ALLOWED_HOSTS is explicitly configured in production
    if not ALLOWED_HOSTS:
        raise RuntimeError("ALLOWED_HOSTS must be set in production (via the ALLOWED_HOSTS env var).")

    # Basic HTTPS / cookie security defaults — can be overridden by env vars when needed
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "1") == "1"
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "1") == "1"
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "1") == "1"
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "1") == "1"
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "1") == "1"

    # Render uses proxies (X-Forwarded-For, X-Forwarded-Proto), so trust proxy headers
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if not host.startswith("*")]
