# Generated by Django 5.1.6 on 2026-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfollow',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
