# Generated by Django 5.1.6 on 2026-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_backfill_person_credited_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfollow',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personfollow',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
