# Generated by Django 4.2.11 on 2026-05-03 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_backfill_follow_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMovieArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='newmoviearrival',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'source_type', 'source_id'), name='uniq_new_movie_arrival'),
        ),
    ]
