# Generated by Django 4.2.11 on 2026-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_newmoviearrival_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='newmoviearrival',
            name='uniq_new_movie_arrival',
        ),
        migrations.AddField(
            model_name='newmoviearrival',
            name='event_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='newmoviearrival',
            name='event_type',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='newmoviearrival',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'event_type', 'source_type', 'source_id'), name='uniq_new_movie_arrival'),
        ),
    ]
