# Generated by Django 5.1.6 on 2026-05-08 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_newmoviearrival_uniq_new_movie_arrival_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='The Dailies', max_length=120)),
                ('issue_date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('parsed', 'Parsed'), ('published', 'Published')], default='draft', max_length=20)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('normalized_text', models.CharField(max_length=64)),
                ('entity_hints', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.newsletterissue')),
            ],
            options={
                'ordering': ['issue', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterItemSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='catalog.newsletteritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.UniqueConstraint(fields=('issue', 'normalized_text'), name='uniq_newsletter_item_text_per_issue'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritem',
            constraint=models.UniqueConstraint(fields=('issue', 'position'), name='uniq_newsletter_item_position_per_issue'),
        ),
        migrations.AddConstraint(
            model_name='newsletteritemseen',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='uniq_newsletter_item_seen'),
        ),
    ]
