# Generated by Django 5.1.6 on 2026-05-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_newsletterissue_newsletteritem_newsletteritemseen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmoviearrival',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
