# Generated by Django 5.1.6 on 2026-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_tmdb_last_sync_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movie',
            new_name='catalog_mov_title_313ee4_idx',
            old_name='movie_title_tmdbid_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='catalog_mov_release_94e35e_idx',
            old_name='movie_rel_dt_tmdbid_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='catalog_mov_tmdb_la_927426_idx',
            old_name='movie_tmdbsync_tmdbid_idx',
        ),
    ]
