# Generated by Django 5.1.6 on 2026-05-30 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_followactivity_company_role_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_accessed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['last_accessed_at', 'tmdb_id'], name='catalog_mov_last_ac_fd853c_idx'),
        ),
    ]
