# Generated by Django 5.1.6 on 2026-07-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		("catalog", "0023_backfill_follow_status_columns"),
	]

	operations = [
		migrations.CreateModel(
			name="DiaryAccount",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("letterboxd_username", models.CharField(blank=True, default="", max_length=80)),
				("last_successful_sync_at", models.DateTimeField(blank=True, null=True)),
				("newest_processed_guid", models.CharField(blank=True, default="", max_length=512)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"user",
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="diary_account",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"ordering": ["user_id"],
			},
		),
		migrations.CreateModel(
			name="DiaryEntry",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("original_title", models.CharField(db_index=True, max_length=255)),
				("original_release_year", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
				("watched_date", models.DateField(db_index=True)),
				("rating", models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
				("liked", models.BooleanField(default=False)),
				("rewatch", models.BooleanField(default=False)),
				("review", models.TextField(blank=True, default="")),
				("rss_guid", models.CharField(blank=True, db_index=True, default="", max_length=512)),
				("tmdb_id", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
				("official_title", models.CharField(blank=True, default="", max_length=255)),
				("release_date", models.DateField(blank=True, null=True)),
				(
					"match_source",
					models.CharField(
						choices=[("AUTO", "Auto"), ("MANUAL", "Manual")],
						default="AUTO",
						max_length=20,
					),
				),
				("manual_lock", models.BooleanField(default=False)),
				("match_candidates", models.JSONField(blank=True, default=list)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				("updated_at", models.DateTimeField(auto_now=True)),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="diary_entries",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"ordering": ["-watched_date", "-created_at", "-id"],
				"constraints": [
					models.UniqueConstraint(
						fields=("user", "original_title", "original_release_year", "watched_date"),
						name="uniq_diary_entry_original_watch",
					),
				],
				"indexes": [
					models.Index(fields=["user", "watched_date"], name="catalog_dia_user_watched_idx"),
					models.Index(fields=["user", "rss_guid"], name="catalog_dia_user_rss_guid_idx"),
					models.Index(fields=["user", "tmdb_id"], name="catalog_dia_user_tmdb_idx"),
				],
			},
		),
	]
