# Generated by Django 5.1.6 on 2026-07-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("catalog", "0024_diary"),
	]

	operations = [
		migrations.AddField(
			model_name="diaryentry",
			name="match_candidates",
			field=models.JSONField(blank=True, default=list),
		),
	]
