# Generated by Django 5.1.6 on 2026-07-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("catalog", "0025_diaryentry_match_candidates"),
	]

	operations = [
		migrations.AddField(
			model_name="diaryentry",
			name="poster_path",
			field=models.CharField(blank=True, default="", max_length=255),
		),
	]
