# Generated by Django 5.1.6 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("catalog", "0026_diaryentry_poster_path"),
	]

	operations = [
		migrations.AddField(
			model_name="movie",
			name="accent_color",
			field=models.CharField(default="#6B7280", max_length=7),
		),
	]
